title: Clothing Store
description: An online store for stylish clothes
theme: minima # You can choose a different theme if you prefer

author:
  name: Your Name
  email: your.email@example.com

permalink: pretty

